return {
	[100013] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100014] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[100015] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100016] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[100017] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[100018] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
}
