return {
	[100880] = {
		interval = 5,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[100467] = {
		interval = 5,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[100550] = {
		interval = 5,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[100840] = {
		interval = 5,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[100874] = {
		interval = 5,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[100863] = {
		interval = 5,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[100924] = {
		interval = 5,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[100925] = {
		interval = 15,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[100671] = {
		interval = 5,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[100672] = {
		interval = 5,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
}
