return {
	[100817] = {
		interval = 20,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_c",
		}
	},
	[105201] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100887] = {
		interval = 40,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_tazers",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[102364] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_tazers",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[105489] = {
		interval = 60,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[105718] = {
		interval = 20,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[105200] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100329] = {
		interval = 20,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100896] = {
		interval = 20,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_tazers",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
}
