return {
	[101622] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100627] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[101975] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100629] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[102010] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[102012] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100666] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[101663] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101983] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[101085] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[101310] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101607] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100335] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101642] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100147] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101972] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101530] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[102009] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100161] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[102011] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[101534] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[101084] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[101309] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[102008] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101978] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101657] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100148] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101034] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
			"single_spooc",
		}
	},
	[101967] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101633] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101636] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101651] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101308] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
}
