return {
	[100912] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[102387] = {
		interval = 30,
		preferred_spawn_groups = {
			"CS_swats",
			"CS_heavys",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[102173] = {
		interval = 30,
		preferred_spawn_groups = {
			"CS_swats",
			"CS_heavys",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[102331] = {
		interval = 30,
		preferred_spawn_groups = {
			"CS_swats",
			"CS_heavys",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100167] = {
		interval = 15,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[101005] = {
		interval = 0,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100154] = {
		interval = 15,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
	[100146] = {
		interval = 15,
		preferred_spawn_groups = {
			"CS_cops",
			"CS_swats",
			"CS_heavys",
			"CS_shields",
			"CS_tazers",
			"CS_tanks",
			"CS_stealth_a",
			"CS_defend_a",
			"CS_defend_b",
			"CS_defend_c",
			"FBI_swats",
			"FBI_heavys",
			"FBI_shields",
			"FBI_spoocs",
			"FBI_tanks",
			"FBI_stealth_a",
			"FBI_stealth_b",
			"FBI_defend_a",
			"FBI_defend_b",
			"FBI_defend_c",
			"FBI_defend_d",
		}
	},
}
